# Generated by Django 4.2.2 on 2023-06-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearstore', '0002_address_cart_cartitem_customer_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
    ]
